shell := "bash"

# check all
ca: 
  cargo check --target x86_64-pc-windows-gnu
  cargo check --target x86_64-unknown-linux-gnu

# list rustup target 
lt: 
  rustup target list  | rg -i installed       

# clean comment on init.lua
cm: 
  sed -i 's/--remove//g' ~/.config/nvim/init.lua

# activate windows
aw:
  just cm

  sed -i \
  -e 's/--remove target = "x86_64-pc-windows-gnu"/target = "x86_64-pc-windows-gnu"/' \
  -e 's/target = "x86_64-unknown-linux-gnu"/--remove target = "x86_64-unknown-linux-gnu"/' \
  ~/.config/nvim/init.lua

  cat ~/.config/nvim/init.lua

# activate linux
al:
  just cm

  sed -i \
  -e 's/--remove target = "x86_64-unknown-linux-gnu"/target = "x86_64-unknown-linux-gnu"/' \
  -e 's/target = "x86_64-pc-windows-gnu"/--remove target = "x86_64-pc-windows-gnu"/' \
  ~/.config/nvim/init.lua

  cat ~/.config/nvim/init.lua
