name: Build Riggler Release

on:
  workflow_dispatch: 
  push:
    branches: [release]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    name: Build on Linux (x86_64)
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust 
        run: |
          sudo apt update
          sudo apt install -y build-essential pkg-config libglib2.0-dev libgtk-3-dev
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env
          rustup default stable
      - name: Build Windows Slint App
        run: |
          cd app
          cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: linux
          path: app/target/release/riggler

  build_windows:
    runs-on: windows-latest
    name: Build on Windows
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          setx PATH "%USERPROFILE%\.cargo\bin;%PATH%"
          rustup default stable
      - name: Build Windows Slint App
        run: |
          cd app
          cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: windows
          path: app\target\release\riggler.exe
